### ISSUE TITLE
Gh pages deploy

### ISSUE THREAD

**Issue by raczmate** [Uni-Sopron/temalabor-o21-I-NEW-Centralized-log-server#1]
A külön `/docs/` mappára kérnénk a beállítást.

**Comment by hegyhati** [comment]
Done, de errorol szepen a console-ba. Ahogy elnezem, baseurl beallitasi hiba lehet. 
https://uni-sopron.github.io/temalabor-o21-I-NEW-Centralized-log-server/

**Comment by raczmate** [comment]
Ohh, igen sejtettem, hogy lesz ezzel gond azért, köszönjük!

**Comment by hegyhati** [comment]
Most mar szuper, nice, koszi
